local t = require("helpers")
local parsers = require("picky.parsers")

t.describe("parsers.file_item", function()
  t.it("splits into a Normal filename and a Comment directory", function()
    local cwd = assert(vim.uv.cwd())
    local item = parsers.file_item(cwd .. "/lua/picky/init.lua")
    t.eq("lua/picky/init.lua", item.text)
    t.eq("init.lua", item.name)
    t.eq("lua/picky", item.dir)
    t.eq(cwd .. "/lua/picky/init.lua", item.path)
    t.eq({ "name", "dir", "text" }, item.fields)
    t.eq({
      { field = "name" },
      { text = " " },
      { field = "dir", hl = "PickyDir" },
    }, item.display)
  end)

  t.it("shows ~ for files under the home directory", function()
    local item = parsers.file_item(vim.fn.expand("~") .. "/note.md")
    t.eq("note.md", item.name)
    t.eq("~", item.dir)
  end)

  t.it("renders the filename alone for files in the cwd root", function()
    local item = parsers.file_item(assert(vim.uv.cwd()) .. "/Makefile")
    t.eq("Makefile", item.name)
    t.eq(nil, item.dir)
    t.eq({ "name", "text" }, item.fields)
    t.eq({ { field = "name" } }, item.display)
  end)
end)

t.describe("parsers.ansi", function()
  t.it("builds a flat item with stripped text and color spans", function()
    local item = assert(parsers.ansi("\27[31mred\27[0m text"))
    t.eq("red text", item.text)
    t.eq("red text", item.id)
    t.eq(1, #item.highlights)
    t.eq(0, item.highlights[1].from)
    t.eq(3, item.highlights[1].to)
  end)

  t.it("ignores empty lines", function()
    t.eq(nil, parsers.ansi(""))
  end)
end)

t.describe("parsers.vimgrep", function()
  t.it("parses path:lnum:col:text", function()
    local item = assert(parsers.vimgrep("lua/picky/session.lua:289:5:local function update_input()"))
    t.eq("lua/picky/session.lua:289:5", item.id)
    t.eq("lua/picky/session.lua", item.path)
    t.eq(289, item.lnum)
    t.eq(5, item.col)
    t.eq("local function update_input()", item.text)
    t.eq({ "path", "text" }, item.fields)
  end)

  t.it("keeps colons in the matched text", function()
    local item = assert(parsers.vimgrep("a.txt:1:1:key: value"))
    t.eq("a.txt", item.path)
    t.eq("key: value", item.text)
  end)

  t.it("returns nil for unstructured lines", function()
    t.eq(nil, parsers.vimgrep("no location here"))
    t.eq(nil, parsers.vimgrep(""))
  end)
end)
